'use client';
import { useEffect, useRef, useState } from 'react';
function fmt(s:number){if(!Number.isFinite(s))return '00:00';const m=Math.floor(s/60),r=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
export default function PremiumAudioPlayer({day,title,onEnded}:{day:number;title:string;onEnded?:()=>void}){
 const ref=useRef<HTMLAudioElement|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const[url,setUrl]=useState(''),[file,setFile]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[duration,setDuration]=useState(0),[speed,setSpeed]=useState(1),[sleep,setSleep]=useState(0);const key=`equilibria-audio-position-${day}`;
 useEffect(()=>{(async()=>{try{const r=await fetch(`/api/audio-url?day=${day}`),d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'L’audio de ce chapitre arrive bientôt.');setUrl(d.url);setFile(d.file||'')}catch(e:any){setError(e.message)}finally{setLoading(false)}})();return()=>{if(timer.current)clearTimeout(timer.current)}},[day]);
 useEffect(()=>{const a=ref.current;if(!a||!url)return;const saved=Number(localStorage.getItem(key)||'0');const meta=()=>{setDuration(a.duration||0);if(saved>0&&saved<a.duration-5){a.currentTime=saved;setCurrent(saved)}};const time=()=>{setCurrent(a.currentTime);if(Math.floor(a.currentTime)%5===0)localStorage.setItem(key,String(a.currentTime))};const end=()=>{setPlaying(false);localStorage.removeItem(key);onEnded?.()};a.addEventListener('loadedmetadata',meta);a.addEventListener('timeupdate',time);a.addEventListener('ended',end);return()=>{a.removeEventListener('loadedmetadata',meta);a.removeEventListener('timeupdate',time);a.removeEventListener('ended',end)}},[url,key,onEnded]);
 async function toggle(){const a=ref.current;if(!a)return;if(a.paused){await a.play();setPlaying(true)}else{a.pause();setPlaying(false)}}
 function jump(n:number){const a=ref.current;if(!a)return;const x=Math.max(0,Math.min(a.duration||0,a.currentTime+n));a.currentTime=x;setCurrent(x)}
 function seek(x:number){const a=ref.current;if(!a)return;a.currentTime=x;setCurrent(x)}
 function rate(x:number){const a=ref.current;if(!a)return;a.playbackRate=x;setSpeed(x)}
 function setTimer(m:number){if(timer.current)clearTimeout(timer.current);setSleep(m);if(!m)return;timer.current=setTimeout(()=>{ref.current?.pause();setPlaying(false);setSleep(0)},m*60000)}
 if(loading)return <div className="premiumPlayer loadingPlayer"><div className="playerPulse"/><p>Préparation de l’immersion...</p></div>;
 if(error)return <div className="premiumPlayer unavailablePlayer"><p className="playerEyebrow">IMMERSION AUDIO</p><h3>Le silence fait aussi partie du voyage.</h3><p>{error}</p></div>;
 return <section className="premiumPlayer"><audio ref={ref} src={url} preload="metadata"/><div className="playerTopline"><div><p className="playerEyebrow">IMMERSION AUDIO</p><h3>{title}</h3></div><div className="playerFile">{file.includes('.m4a')?'M4A':'MP3'}</div></div><div className="playerMainControls"><button className="playerRoundButton secondary" onClick={()=>jump(-15)}>−15</button><button className="playerRoundButton primary" onClick={toggle}>{playing?'Ⅱ':'▶'}</button><button className="playerRoundButton secondary" onClick={()=>jump(15)}>+15</button></div><div className="playerTimeline"><span>{fmt(current)}</span><input type="range" min={0} max={duration||0} step={.1} value={current} onChange={e=>seek(Number(e.target.value))}/><span>{fmt(duration)}</span></div><div className="playerOptions"><div className="speedControls"><span>Vitesse</span>{[.75,1,1.25,1.5].map(v=><button key={v} className={speed===v?'active':''} onClick={()=>rate(v)}>{v}×</button>)}</div><div className="sleepControls"><label>Minuteur</label><select value={sleep} onChange={e=>setTimer(Number(e.target.value))}><option value={0}>Désactivé</option><option value={10}>10 min</option><option value={20}>20 min</option><option value={30}>30 min</option><option value={45}>45 min</option></select></div></div><p className="playerHint">Votre position est mémorisée automatiquement.</p></section>
}
